# Generated by Django 5.0.3 on 2024-04-01 14:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b185d9a9-788e-460a-a3fe-94e40c687a42'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('bbd926fa-2970-4103-bd07-07400502267f'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('76fc6815-c724-479f-a336-946e4ea57f7a'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='taggedshopproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cefbcb15-81f1-491a-8803-003a9110d01d'), editable=False, unique=True),
        ),
    ]
