# Generated by Django 5.0.3 on 2024-03-27 10:01

import uuid
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_profile_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c98354e7-fbfe-4da3-bc7f-cf8e8473121f'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fc7f1586-0501-4824-8b74-fcd2ecd2e017'), editable=False, unique=True),
        ),
    ]
