# Generated by Django 5.0.3 on 2024-04-02 04:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ab14b268-cbeb-4372-a338-727c410bcf60'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('af1a81fa-75a7-4788-9cd9-e599f312ef59'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='taggedproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('582b5bda-c228-414f-a761-193e43aafe0c'), editable=False, unique=True),
        ),
    ]
