# Generated by Django 5.0.3 on 2024-03-28 14:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('04520b9e-91ac-42a9-bc21-af4395fc9d46'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7de0ca43-4304-47a1-b7b2-2a71f1307831'), editable=False, unique=True),
        ),
    ]
