# Generated by Django 5.0.3 on 2024-04-02 04:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_uuid_alter_tag_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a39e160c-1b58-4f2f-911e-93a9117f1c45'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('16a3c1f1-69c1-476a-ac4d-6bf3f14897ee'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='taggedproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4223677a-8b78-484e-a88a-58b720a1cf44'), editable=False, unique=True),
        ),
    ]
