# Generated by Django 5.0.3 on 2024-04-12 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_tag_producttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.ManyToManyField(through='product.ProductInventory', to='product.inventory'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
