# Generated by Django 5.0.3 on 2024-03-31 04:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_uuid_alter_shopproduct_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e4d227f8-0d1c-43b8-9475-7b24dcc1c3fa'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('82119162-1cb8-4182-9fd5-efcbae15016a'), editable=False, unique=True),
        ),
    ]
