# Generated by Django 5.0.3 on 2024-04-02 04:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_uuid_alter_tag_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5629bd17-6ff0-4163-8940-4d227e995f4f'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('26c7e690-7887-4f37-9cc0-998c8b071b88'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='taggedproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('61371d6a-7260-4850-aa1c-dcfc537eff42'), editable=False, unique=True),
        ),
    ]
