# Generated by Django 5.0.3 on 2024-04-02 04:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_uuid_alter_tag_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantiry',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('609f9a14-879c-4180-989e-d8e40d2891b4'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('135336be-1cf8-444a-a7e2-cecc67716627'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='taggedproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d581d1a1-7176-44f9-9af6-a43189de7aad'), editable=False, unique=True),
        ),
    ]
