# Generated by Django 5.0.3 on 2024-04-02 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_quantiry_product_quantity_alter_product_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('45231215-7e0b-4eea-b862-19456e750909'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d718e1a3-cb15-403f-bcf3-d54acb2155f7'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='taggedproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0e02807e-b85d-4408-9379-01f13726aee0'), editable=False, unique=True),
        ),
    ]
