# Generated by Django 5.0.3 on 2024-03-31 05:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_uuid_alter_shopproduct_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('70f55417-db8d-4172-a526-f6b0cd937a2b'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ecbe0a87-53e9-476a-9d85-2fe6e2b01b82'), editable=False, unique=True),
        ),
    ]
