# Generated by Django 5.0.3 on 2024-04-02 09:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_uuid_alter_tag_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1288e61e-136d-47b6-b103-cb605edaea79'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f0509231-c5fc-4cdf-ba96-fe96231fa73d'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='taggedproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b0e7c23c-c6db-487f-b357-a6315a215b4c'), editable=False, unique=True),
        ),
    ]
