# Generated by Django 5.0.3 on 2024-04-02 13:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_uuid_alter_tag_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('211f5596-974f-42d7-9705-d98300ad3e17'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d2fa72d5-f0da-46d5-9822-68eab6456ecc'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='taggedproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1cf545fd-5d56-49ec-aac7-84449adbe040'), editable=False, unique=True),
        ),
    ]
