# Generated by Django 5.0.3 on 2024-03-31 06:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_uuid_alter_shopproduct_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('25c62fee-f3c1-4487-a243-6e0715e3e965'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c4efacdd-fbbf-40f0-b795-4020a38d8536'), editable=False, unique=True),
        ),
    ]
