# Generated by Django 5.0.3 on 2024-04-03 03:30

import django.db.models.deletion
import uuid
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_uuid_alter_tag_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5f6469d6-c001-4c49-8161-00e80a742f93'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('bdbe8522-8020-4a6c-b0c6-8a31f7557bc3'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='taggedproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('49b33252-30e1-49cd-a74d-631cd6e3944c'), editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('bb85555d-d57d-42ce-bad8-4653c794d896'), editable=False, unique=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
    ]
