# Generated by Django 5.0.3 on 2024-04-03 03:47

import uuid
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_uuid_alter_tag_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d49d723c-b7ec-42b1-8278-4756c5915bb2'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('53abbe0c-6c73-4aab-8e34-31121ed7a9bd'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('bf06763c-4fa9-43aa-9a11-fae9a62f9945'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='taggedproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1b0d9b46-6078-4849-aa77-2d0090a5ea07'), editable=False, unique=True),
        ),
    ]
