# Generated by Django 5.0.3 on 2024-04-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrating',
            name='rating',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20),
        ),
    ]
