# Generated by Django 5.0.3 on 2024-04-15 06:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_customerrating_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerRating',
            new_name='CustomerReview',
        ),
    ]
