# Generated by Django 5.0.3 on 2024-04-15 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_customerrating_customerreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
