# Generated by Django 5.0.3 on 2024-04-15 07:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_customerreview_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerreview',
            unique_together={('user', 'product')},
        ),
    ]
