# Generated by Django 5.0.3 on 2024-04-03 08:20

import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_image_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='product.tag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_profile_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/product_profile'),
        ),
    ]
