# Generated by Django 5.0.3 on 2024-04-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_image_product_delete_producttag_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='farce',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
