# Generated by Django 5.0.3 on 2024-04-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_productinventory_inventory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='farce',
        ),
    ]
