# Generated by Django 5.0.3 on 2024-04-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_customerreview_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreview',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
