# Generated by Django 5.0.3 on 2024-04-24 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_remove_customerreview_average_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_profile_image',
            new_name='profile_image',
        ),
    ]
