# Generated by Django 5.0.3 on 2024-04-02 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_member_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='shop.shop'),
        ),
    ]
