# Generated by Django 5.0.3 on 2024-03-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_role_uuid_alter_shop_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
