# Generated by Django 5.0.3 on 2024-04-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected',
            field=models.BooleanField(default=True),
        ),
    ]
